package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/BurntSushi/toml"

	"github.com/ethereum/go-ethereum/internal/cli/server"
)

var (
	// TOML keys supported here:
	// - quoted keys: "a.b", 'a.b'
	// - dotted bare keys: a.b.c
	// - bare key segments: [A-Za-z0-9_-]+
	keyValueRe = regexp.MustCompile(`^\s*("([^"\\]|\\.)*"|'[^']*'|[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]+)*)\s*=`)
)

type docsIndex struct {
	keyDocs     map[string]string
	sectionDocs map[string]string
}

func main() {
	var (
		root   string
		dryRun bool
	)

	flag.StringVar(&root, "root", ".", "Repository root")
	flag.BoolVar(&dryRun, "dry-run", false, "Only print files that would be updated")
	flag.Parse()

	targets, err := collectTargets(root)
	if err != nil {
		exitErr(err)
	}
	if len(targets) == 0 {
		exitErr(fmt.Errorf("no config.toml files found"))
	}

	docIndex, err := buildDocsIndex(filepath.Join(root, "internal", "cli", "server", "config.go"))
	if err != nil {
		exitErr(err)
	}

	updated := 0
	for _, target := range targets {
		current, err := os.ReadFile(target)
		if err != nil {
			if os.IsNotExist(err) {
				current = nil
			} else {
				exitErr(fmt.Errorf("read %s: %w", target, err))
			}
		}

		defaultConfig := loadDefaultConfig()
		renderedConfigText, err := renderConfigWithComments(defaultConfig, docIndex)
		if err != nil {
			exitErr(err)
		}

		if bytes.Equal(current, renderedConfigText) {
			continue
		}

		if dryRun {
			fmt.Printf("would update %s\n", target)
			updated++
			continue
		}

		if err := os.WriteFile(target, renderedConfigText, 0o600); err != nil {
			exitErr(fmt.Errorf("write %s: %w", target, err))
		}
		fmt.Printf("updated %s\n", target)
		updated++
	}

	if dryRun {
		fmt.Printf("dry-run complete: %d files would be updated\n", updated)
		return
	}

	fmt.Printf("complete: %d files updated\n", updated)
}

func collectTargets(root string) ([]string, error) {
	target := filepath.Join(root, "docs", "cli", "default_config.toml")
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return nil, fmt.Errorf("ensure target directory: %w", err)
	}
	return []string{target}, nil
}

func loadDefaultConfig() *server.Config {
	cfg := server.DefaultConfig()
	cfg.Chain = ""
	cfg.Identity = ""
	cfg.DataDir = "/var/lib/bor"
	return cfg
}

func renderConfigWithComments(cfg *server.Config, docIndex docsIndex) ([]byte, error) {
	fillRawFields(cfg)

	var buf bytes.Buffer
	if err := toml.NewEncoder(&buf).Encode(cfg); err != nil {
		return nil, fmt.Errorf("encode config: %w", err)
	}

	commented, err := annotateTOML(buf.String(), docIndex)
	if err != nil {
		return nil, err
	}

	header := strings.Join([]string{
		"# Auto-generated by cmd/generate-default-config/main.go",
		"# Source of truth: internal/cli/server/DefaultConfig and struct field docs.",
		"",
		"",
	}, "\n")

	return []byte(header + commented), nil
}

func fillRawFields(cfg *server.Config) {
	if cfg.JsonRPC.RPCEVMTimeoutRaw == "" {
		cfg.JsonRPC.RPCEVMTimeoutRaw = cfg.JsonRPC.RPCEVMTimeout.String()
	}
	if cfg.JsonRPC.HttpTimeout.ReadTimeoutRaw == "" {
		cfg.JsonRPC.HttpTimeout.ReadTimeoutRaw = cfg.JsonRPC.HttpTimeout.ReadTimeout.String()
	}
	if cfg.JsonRPC.HttpTimeout.ReadHeaderTimeoutRaw == "" {
		cfg.JsonRPC.HttpTimeout.ReadHeaderTimeoutRaw = cfg.JsonRPC.HttpTimeout.ReadHeaderTimeout.String()
	}
	if cfg.JsonRPC.HttpTimeout.WriteTimeoutRaw == "" {
		cfg.JsonRPC.HttpTimeout.WriteTimeoutRaw = cfg.JsonRPC.HttpTimeout.WriteTimeout.String()
	}
	if cfg.JsonRPC.HttpTimeout.IdleTimeoutRaw == "" {
		cfg.JsonRPC.HttpTimeout.IdleTimeoutRaw = cfg.JsonRPC.HttpTimeout.IdleTimeout.String()
	}
	if cfg.JsonRPC.Http.ExecutionPoolRequestTimeoutRaw == "" {
		cfg.JsonRPC.Http.ExecutionPoolRequestTimeoutRaw = cfg.JsonRPC.Http.ExecutionPoolRequestTimeout.String()
	}
	if cfg.JsonRPC.Ws.ExecutionPoolRequestTimeoutRaw == "" {
		cfg.JsonRPC.Ws.ExecutionPoolRequestTimeoutRaw = cfg.JsonRPC.Ws.ExecutionPoolRequestTimeout.String()
	}
	if cfg.JsonRPC.TxSyncDefaultTimeoutRaw == "" {
		cfg.JsonRPC.TxSyncDefaultTimeoutRaw = cfg.JsonRPC.TxSyncDefaultTimeout.String()
	}
	if cfg.JsonRPC.TxSyncMaxTimeoutRaw == "" {
		cfg.JsonRPC.TxSyncMaxTimeoutRaw = cfg.JsonRPC.TxSyncMaxTimeout.String()
	}
	if cfg.TxPool.RejournalRaw == "" {
		cfg.TxPool.RejournalRaw = cfg.TxPool.Rejournal.String()
	}
	if cfg.TxPool.LifeTimeRaw == "" {
		cfg.TxPool.LifeTimeRaw = cfg.TxPool.LifeTime.String()
	}
	if cfg.TxPool.RebroadcastIntervalRaw == "" {
		cfg.TxPool.RebroadcastIntervalRaw = cfg.TxPool.RebroadcastInterval.String()
	}
	if cfg.TxPool.RebroadcastMaxAgeRaw == "" {
		cfg.TxPool.RebroadcastMaxAgeRaw = cfg.TxPool.RebroadcastMaxAge.String()
	}
	if cfg.Sealer.GasPriceRaw == "" && cfg.Sealer.GasPrice != nil {
		cfg.Sealer.GasPriceRaw = cfg.Sealer.GasPrice.String()
	}
	if cfg.Sealer.RecommitRaw == "" {
		cfg.Sealer.RecommitRaw = cfg.Sealer.Recommit.String()
	}
	if cfg.Sealer.BlockTimeRaw == "" {
		cfg.Sealer.BlockTimeRaw = cfg.Sealer.BlockTime.String()
	}
	if cfg.Gpo.MaxPriceRaw == "" && cfg.Gpo.MaxPrice != nil {
		cfg.Gpo.MaxPriceRaw = cfg.Gpo.MaxPrice.String()
	}
	if cfg.Gpo.IgnorePriceRaw == "" && cfg.Gpo.IgnorePrice != nil {
		cfg.Gpo.IgnorePriceRaw = cfg.Gpo.IgnorePrice.String()
	}
	if cfg.Cache.TrieTimeoutRaw == "" {
		cfg.Cache.TrieTimeoutRaw = cfg.Cache.TrieTimeout.String()
	}
	if cfg.P2P.TxArrivalWaitRaw == "" {
		cfg.P2P.TxArrivalWaitRaw = cfg.P2P.TxArrivalWait.String()
	}
}

func buildDocsIndex(configPath string) (docsIndex, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, configPath, nil, parser.ParseComments)
	if err != nil {
		return docsIndex{}, fmt.Errorf("parse config source: %w", err)
	}

	structs := map[string]*ast.StructType{}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			structs[ts.Name.Name] = st
		}
	}

	keyDocs := map[string]string{}
	sectionDocs := map[string]string{}
	visited := map[string]bool{}

	var walkStruct func(typeName string, prefix []string)
	walkStruct = func(typeName string, prefix []string) {
		st, ok := structs[typeName]
		if !ok {
			return
		}

		visitKey := typeName + ":" + strings.Join(prefix, ".")
		if visited[visitKey] {
			return
		}
		visited[visitKey] = true

		for _, field := range st.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			tagValue := parseTag(field.Tag)
			tagName, isBlock := parseTOMLTag(tagValue)
			if tagName == "" || tagName == "-" {
				continue
			}

			doc := normalizeDoc(field.Doc, field.Comment)
			path := joinPath(prefix, tagName)

			if isBlock {
				if doc != "" {
					sectionDocs[path] = doc
				}
				if nested := resolveStructName(field.Type); nested != "" {
					walkStruct(nested, append(prefix, tagName))
				}
				continue
			}

			if doc != "" {
				keyDocs[path] = doc
			}
		}
	}

	walkStruct("Config", nil)
	addRawFieldDocs(keyDocs)

	return docsIndex{keyDocs: keyDocs, sectionDocs: sectionDocs}, nil
}

func annotateTOML(content string, index docsIndex) (string, error) {
	scanner := bufio.NewScanner(strings.NewReader(content))
	lines := make([]string, 0, 512)
	section := []string{}

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			lines = append(lines, line)
			continue
		}

		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			section = parseSection(trimmed)
			sectionPath := strings.Join(section, ".")
			if doc := index.sectionDocs[sectionPath]; doc != "" {
				lines = append(lines, formatComment(doc, leadingWhitespace(line))...)
			}
			lines = append(lines, line)
			continue
		}

		keyPath, ok := parseKeyPath(line, section)
		if !ok {
			lines = append(lines, line)
			continue
		}

		if doc := index.keyDocs[keyPath]; doc != "" {
			lines = append(lines, formatComment(doc, leadingWhitespace(line))...)
		}
		lines = append(lines, line)
	}

	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("scan toml: %w", err)
	}

	return strings.Join(lines, "\n") + "\n", nil
}

func formatComment(doc string, indent string) []string {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return nil
	}

	return []string{indent + "# " + doc}
}

func leadingWhitespace(line string) string {
	i := 0
	for i < len(line) && (line[i] == ' ' || line[i] == '\t') {
		i++
	}
	return line[:i]
}

func parseKeyPath(line string, section []string) (string, bool) {
	m := keyValueRe.FindStringSubmatch(line)
	if len(m) < 2 {
		return "", false
	}
	key := strings.TrimSpace(m[1])
	key = trimTOMLQuotes(key)

	if len(section) == 0 {
		return key, true
	}
	parts := append(append([]string{}, section...), key)
	return strings.Join(parts, "."), true
}

func parseSection(line string) []string {
	if strings.HasPrefix(line, `["`) && strings.HasSuffix(line, `"]`) {
		return []string{trimTOMLQuotes(strings.Trim(line, "[]"))}
	}
	if strings.HasPrefix(line, `['`) && strings.HasSuffix(line, `']`) {
		return []string{trimTOMLQuotes(strings.Trim(line, "[]"))}
	}

	inside := strings.Trim(line, "[]")
	rawParts := strings.Split(inside, ".")
	parts := make([]string, 0, len(rawParts))
	for _, raw := range rawParts {
		parts = append(parts, trimTOMLQuotes(strings.TrimSpace(raw)))
	}
	return parts
}

func trimTOMLQuotes(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

func addRawFieldDocs(keyDocs map[string]string) {
	rawAliases := map[string]string{
		"jsonrpc.evmtimeout":             "Sets a timeout used for eth_call (0=infinite)",
		"jsonrpc.txsync.defaulttimeout":  "Default timeout for eth_sendRawTransactionSync (e.g. 2s, 500ms)",
		"jsonrpc.txsync.maxtimeout":      "Maximum allowed timeout for eth_sendRawTransactionSync (e.g. 5m)",
		"jsonrpc.timeouts.read":          "ReadTimeout is the maximum duration for reading the entire request, including the body.",
		"jsonrpc.timeouts.readheader":    "ReadHeaderTimeout is the amount of time allowed to read request headers.",
		"jsonrpc.timeouts.write":         "WriteTimeout is the maximum duration before timing out writes of the response.",
		"jsonrpc.timeouts.idle":          "IdleTimeout is the maximum amount of time to wait for the next request when keep-alives are enabled.",
		"jsonrpc.http.ep-requesttimeout": "ExecutionPoolRequestTimeout is timeout used by execution pool for rpc execution",
		"jsonrpc.ws.ep-requesttimeout":   "ExecutionPoolRequestTimeout is timeout used by execution pool for rpc execution",
		"txpool.rejournal":               "Rejournal is the time interval to regenerate the local transaction journal",
		"txpool.lifetime":                "lifetime is the maximum amount of time non-executable transaction are queued",
		"txpool.rebroadcast-interval":    "RebroadcastInterval is the interval between rebroadcast checks",
		"txpool.rebroadcast-max-age":     "RebroadcastMaxAge is the maximum age for rebroadcast eligibility",
		"miner.gasprice":                 "GasPrice is the minimum gas price for mining a transaction",
		"miner.recommit":                 "The time interval for miner to re-create mining work.",
		"miner.blocktime":                "BlockTime is the block time defined by the miner. Needs to be larger or equal to the consensus block time.",
		"gpo.maxprice":                   "MaxPrice is an upper bound gas price",
		"gpo.ignoreprice":                "IgnorePrice is a lower bound gas price",
		"cache.timeout":                  "Time after which the Merkle Patricia Trie is stored to disc from memory",
		"p2p.txarrivalwait":              "TxArrivalWait sets the maximum duration the transaction fetcher will wait for an announced transaction to arrive",
	}

	for key, value := range rawAliases {
		if _, ok := keyDocs[key]; !ok {
			keyDocs[key] = value
		}
	}
}

func parseTag(tagLit *ast.BasicLit) string {
	if tagLit == nil {
		return ""
	}
	return strings.Trim(tagLit.Value, "`")
}

func parseTOMLTag(tag string) (name string, isBlock bool) {
	if tag == "" {
		return "", false
	}

	chunks := strings.Split(tag, " ")
	for _, chunk := range chunks {
		chunk = strings.TrimSpace(chunk)
		if !strings.HasPrefix(chunk, `toml:"`) {
			continue
		}
		value := strings.TrimPrefix(chunk, `toml:"`)
		value = strings.TrimSuffix(value, `"`)
		parts := strings.Split(value, ",")
		if len(parts) == 0 {
			return "", false
		}
		name = strings.TrimSpace(parts[0])
		for _, p := range parts[1:] {
			if strings.TrimSpace(p) == "block" {
				isBlock = true
			}
		}
		return name, isBlock
	}
	return "", false
}

func resolveStructName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	case *ast.Ident:
		return t.Name
	}
	return ""
}

func normalizeDoc(groups ...*ast.CommentGroup) string {
	for _, group := range groups {
		if group == nil {
			continue
		}
		lines := make([]string, 0, len(group.List))
		for _, c := range group.List {
			txt := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			txt = strings.TrimSpace(strings.TrimPrefix(txt, "/*"))
			txt = strings.TrimSpace(strings.TrimSuffix(txt, "*/"))
			if txt == "" {
				continue
			}
			lines = append(lines, txt)
		}
		if len(lines) == 0 {
			continue
		}
		return strings.Join(lines, " ")
	}
	return ""
}

func joinPath(prefix []string, key string) string {
	if len(prefix) == 0 {
		return key
	}
	parts := append(append([]string{}, prefix...), key)
	return strings.Join(parts, ".")
}

func exitErr(err error) {
	fmt.Fprintf(os.Stderr, "error: %v\n", err)
	os.Exit(1)
}
